steps:
- task: vsintellinav.vsck-service-endpoint.build-task.upload-cache-build-task@0
  displayName: 'VS IntelliNav Upload'
  inputs:
    vsckEndpoint: 'azuretools-dev' # name of the IntelliNav service connection
    nugetpat: 'azuretools-nuget' # name of the NuGet service connection
    language: 'typescript' # languages in your repo, separated by commas
    githubpat: 'GitHub connection' # if your repo is on GitHub, this is the name of the GitHub service connection (GitHub organization by default)
  # this failing shouldn't block builds
  continueOnError: true
